package zw.co.hyperfeeds.bookings;

import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
import java.math.BigDecimal; import java.time.*; import java.util.*;

@RestController @RequestMapping("/chicks")
public class ChickBookingController {
 private final JdbcClient jdbc; public ChickBookingController(JdbcClient jdbc){this.jdbc=jdbc;}
 @GetMapping("/availability") public List<Batch> availability(@RequestParam UUID branchId){return jdbc.sql("select id,branch_id,breed,hatch_date,available_quantity-reserved_quantity available_quantity,price_per_chick,currency from chick_batches where branch_id=:b and active and hatch_date>=current_date and available_quantity>reserved_quantity order by hatch_date,breed").param("b",branchId).query(Batch.class).list();}
 @PostMapping("/batches") @PreAuthorize("hasRole('ADMIN') or (hasRole('BRANCH_MANAGER') and @branchAccess.canAccess(authentication,#r.branchId))") @ResponseStatus(HttpStatus.CREATED)
 public UUID batch(@Valid @RequestBody BatchRequest r){UUID id=UUID.randomUUID();jdbc.sql("insert into chick_batches(id,branch_id,breed,hatch_date,available_quantity,price_per_chick,currency) values(:id,:b,:breed,:date,:qty,:price,:currency)").param("id",id).param("b",r.branchId).param("breed",r.breed).param("date",r.hatchDate).param("qty",r.quantity).param("price",r.pricePerChick).param("currency",r.currency.toUpperCase()).update();return id;}
 @PostMapping("/bookings") @Transactional @ResponseStatus(HttpStatus.CREATED)
 public Booking book(Authentication auth,@Valid @RequestBody BookingRequest r){UUID user=zw.co.hyperfeeds.identity.CurrentUser.id(auth);int changed=jdbc.sql("update chick_batches set reserved_quantity=reserved_quantity+:q where id=:id and active and available_quantity-reserved_quantity>=:q").param("q",r.quantity).param("id",r.batchId).update();if(changed==0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Requested chick quantity is unavailable");UUID id=UUID.randomUUID();String ref="CHK-"+id.toString().substring(0,8).toUpperCase();Instant expiry=Instant.now().plus(Duration.ofHours(24));jdbc.sql("insert into chick_bookings(id,reference,user_id,batch_id,quantity,status,expires_at) values(:id,:ref,:u,:batch,:q,'HELD',:expiry)").param("id",id).param("ref",ref).param("u",user).param("batch",r.batchId).param("q",r.quantity).param("expiry",expiry).update();return new Booking(id,ref,"HELD",expiry);}
 @GetMapping("/bookings") public List<Map<String,Object>> mine(Authentication a){return jdbc.sql("select id,reference,batch_id,quantity,status,expires_at,created_at from chick_bookings where user_id=:u order by created_at desc").param("u",zw.co.hyperfeeds.identity.CurrentUser.id(a)).query().listOfRows();}
 @DeleteMapping("/bookings/{id}") @Transactional @ResponseStatus(HttpStatus.NO_CONTENT) public void cancel(Authentication a,@PathVariable UUID id){UUID user=zw.co.hyperfeeds.identity.CurrentUser.id(a);Map<String,Object>b=jdbc.sql("select batch_id,quantity from chick_bookings where id=:id and user_id=:u and status='HELD' for update").param("id",id).param("u",user).query().listOfRows().stream().findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.CONFLICT,"Booking cannot be cancelled"));jdbc.sql("update chick_bookings set status='CANCELLED',updated_at=now() where id=:id").param("id",id).update();jdbc.sql("update chick_batches set reserved_quantity=reserved_quantity-:q where id=:id").param("q",b.get("quantity")).param("id",b.get("batch_id")).update();}
 public record Batch(UUID id,UUID branchId,String breed,LocalDate hatchDate,int availableQuantity,BigDecimal pricePerChick,String currency){} public record BatchRequest(@NotNull UUID branchId,@NotBlank String breed,@NotNull LocalDate hatchDate,@Min(1) int quantity,@DecimalMin("0") BigDecimal pricePerChick,@Pattern(regexp="[A-Za-z]{3}") String currency){} public record BookingRequest(@NotNull UUID batchId,@Min(1) int quantity){} public record Booking(UUID id,String reference,String status,Instant expiresAt){}
}
