package zw.co.hyperfeeds.commerce;
import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.stereotype.Component;import org.springframework.web.server.ResponseStatusException;import zw.co.paynow.constants.MobileMoneyMethod;import zw.co.paynow.core.Paynow;import zw.co.paynow.responses.MobileInitResponse;import java.math.BigDecimal;
@Component class PaynowPaymentGateway implements PaymentGateway{
 private final String id,key,resultUrl;PaynowPaymentGateway(@Value("${hyperfeeds.paynow.integration-id}")String id,@Value("${hyperfeeds.paynow.integration-key}")String key,@Value("${hyperfeeds.paynow.result-url}")String resultUrl){this.id=id;this.key=key;this.resultUrl=resultUrl;}
 public Payment start(String reference,BigDecimal amount,String currency,String phone){if(id.isBlank()||key.isBlank())throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Paynow is not configured");if(!"USD".equalsIgnoreCase(currency))throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"Paynow checkout currently supports USD");String local=localNumber(phone);var paynow=new Paynow(id,key,resultUrl);var payment=paynow.createPayment(reference);payment.add("Hyperfeeds order "+reference,amount.doubleValue());MobileInitResponse response;try{response=paynow.sendMobile(payment,local,method(local));}catch(Exception e){throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Paynow could not initiate payment",e);}if(!response.success())throw new ResponseStatusException(HttpStatus.FAILED_DEPENDENCY,"Paynow rejected payment: "+response.getErrors());return new Payment(response.getPaynowReference(),response.pollUrl(),response.instructions());}
 public PaymentStatus poll(String pollUrl){var status=new Paynow(id,key).pollTransaction(pollUrl);return new PaymentStatus(status.isPaid(),status.getStatus().name(),status.getPaynowReference());}
 private static String localNumber(String p){if(p.startsWith("+263"))return "0"+p.substring(4);if(p.startsWith("263"))return "0"+p.substring(3);if(p.matches("0\\d{9}"))return p;throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Paynow mobile payments require a Zimbabwe number");}
 private static MobileMoneyMethod method(String p){return switch(p.substring(1,3)){case"77","78"->MobileMoneyMethod.ECOCASH;case"71"->MobileMoneyMethod.ONEMONEY;case"73"->MobileMoneyMethod.TELECASH;default->throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unsupported mobile-money number");};}
}
